# Generated by Django 4.0 on 2022-01-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSystem', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='userfeedback',
        ),
    ]
