# Generated by Django 4.0 on 2022-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSystem', '0004_rename_feedback_feedback_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
