# Generated by Django 4.0 on 2022-02-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSystem', '0009_attendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='user_attendence',
            new_name='attendence',
        ),
    ]
