# Generated by Django 4.0 on 2022-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSystem', '0011_rename_attendence_userattendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50)),
                ('usermail', models.CharField(max_length=50)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
            ],
        ),
    ]
