# Generated by Django 4.0 on 2022-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSystem', '0012_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endtime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='starttime',
            field=models.DateField(),
        ),
    ]
