# Generated by Django 3.2.8 on 2022-09-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSystem', '0014_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
